---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    name: test-pod
  ports:
    - name: nginx-http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: mysql-http
      protocol: TCP
      port: 3306
      targetPort: 3306
