apiVersion: v1
kind: Pod
metadata:
  name: test-pod 
  labels:
    name: test-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: mysql 
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: VMware1!
    volumeMounts:
    - name: mysql
      mountPath: /var/lib/mysql
    ports:
    - containerPort: 3306
  volumes:
  - name: mysql
    emptyDir: {}
