apiVersion: v1
kind: Secret
metadata:
  name: tutorial-registry-credentials
  annotations:
    build.pivotal.io/docker: gcr.io
type: kubernetes.io/basic-auth
stringData:
  username: _json_key
  password: |
    {
      "type": "service_account",
      "project_id": "waynean-shawnho",
      "private_key_id": "c00ed7b490ac22ebece2f74f6e67c213bbc67263",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDt5Wmsb7YYi5mo\nGidd/MSpLTKIKTjDujarVvkMnS5nkYSTH1BJo/Tnhd8ohn6Wx+j6Lfxhp/+sIcgu\nqxA5oiobtxrHZxQ6Sg7C22nzlm1gM/TTO1qQ7L874sv5PDlteReoptw6f8uJZ9Rc\nPlatey5Ho54fE0hshseTlKsthGP4ri8Mm6cf3XdOS57E9Z1iAJ9KKYZ5iV65zymG\nfSwbrPpAbbWv73bMlpbf1kFRWJVO1W0rtfKtxIF4HJOidQzqKwdY4hJY0PpJ60Fb\nUBRXGeonQgmqfFhpt+9jZ4mg+lkGZqH1tUsn7XIwcyjIcXZ8VdVIu7d9HMYqOIf3\nGZri7wVLAgMBAAECggEAb+JaAUnmzAN36FookqkLOv+xSN2OP2toQ8wbRIX2KaqE\nPgdXpNKyH2NUUYRzq+loVqVjEfDHq8aVlfFJJ7nvcOp8czS1DDcBWz6DRZdFaJ32\n8pNzJD7cL8eaI+Vhou11JZIYeIDbEowdEacV7/BDk1jNyJKymKwI2A1vNnCR7gXh\ngN/MxsZab5v1au30FRswNClpbm6HJkB6ybvukQovnSV0MQ4w9eOsQN74DYS2IeHQ\nQExHhmmrtpAqut4NFY+K+KA8z425Lk7RnYcsDMqYwYFcPnkmoeYITiaMdWaLsGiv\n+ANVQYhCSKFeOOQaGUVtAZSN46z+4+a5oKjqY+No6QKBgQD/e07wVUcGBQm7SxMF\nqNDAC/yhveTwogF2BZgZUFQQD3r7AVdrqqPmLhJ42c2hdyTURjM/JogDpPZHrBII\n63sBYBxAb7rVMHY0tywtoQM0to46wprrp1DJh3NMqDNqlccpYeK50mhi8nb4JYxX\n7JzWU/0E//oil7kTcZ2GXsqHcwKBgQDuYPiMOoRtBpOaa7mhFmUDUuBMW/6/tLIU\nnG0WgdYZmeBsy8S08tux5fnpVAi4GGQdJFAxLrJeNA+CALAEdYTquUl3/t4iTvl4\nfr3mNHc/rZtFdzt4J39guli5CqR2W46HT1gmIFBXVOlZk6OXnvz4kad5ltin9V8F\nfzruMQekyQKBgQCEcLHtWOfmsPnog/SqfGcrB4vBdSWXsQQ84I2GoePSJ5RDRuDA\nyccJblzZFV/KEm+fM30hgaIE8aFSals3EIvFnMNIjCM4nVTJ4yMdzFhTHUgCIhwZ\nibURpAwbcx6kZFzIkRvt5KuEj9korp5gfiKX4RZLXz+WazzgXYehvsYTDQKBgQCH\nqEfKBcM3CHcXeha5xbTWn2NmETR4hKyTbjHmjRz6lMdTIuNe1paQNwBx+JC9s6PF\nsdSxKJH5akcpBJsm7nol2iwlTbW8cJUoLXiEeXcjlfi3H5OIXXHv6hxzscrGUHRc\nLJtNlzYhfQEPKSYAM0pjawCUAXRqoQjiZ/VxeBWRgQKBgQDus7XJ6eHkpMmMMv7c\n8zQw57N1hG4Y4iylRSUPqSZSHxQ0sWdMPVNF9RAOA0FtzQ/s6H/QsSvB3esWgeKB\ntCIrQgDIRrua97s59GDSHT9T6ulvJrIyRsqyrWckxAmHF7lD3YJmJHbJZKN6KKhj\nQJnAH0mFlVXo3Y77RC2v4475pA==\n-----END PRIVATE KEY-----\n",
      "client_email": "kpack-sa@waynean-shawnho.iam.gserviceaccount.com",
      "client_id": "106351626530903095012",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/kpack-sa%40waynean-shawnho.iam.gserviceaccount.com"
    } 
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: tutorial-service-account
secrets:
 - name: tutorial-registry-credentials