---
- name: "Install Istio"
  hosts: localhost
  connection: local
  tasks:
    - name: "Install istio using demo profile with global mtls enable"
      shell: |
        istioctl manifest apply -y --set profile=demo --set values.global.mtls.enabled=false --set values.global.mtls.auto=true 
      tags:
      - istio
    - name: "Label namespace to have istio-injection on"
      shell: |
        kubectl label ns default istio-injection=enabled --overwrite
      tags:
      - bookinfo
      
    - name: "Install bookinfo application"
      shell: |
        kubectl apply -f bookinfo/0-bookinfo.yaml
        kubectl apply -f bookinfo/0-bookinfo-gateway.yaml
      tags:
      - bookinfo
    
    - name: "Enable Global MTLS"
      shell: |
        kubectl apply -f bookinfo/peer-authentication-global.yaml
      tags:
      - enable_global_mtls

    - name: "Policy precedence by local policy definition"
      shell: |
        kubectl apply -f bookinfo/peer-authentication-svc.yaml
      tags:
      - disable_service_mtls
    - name: "Enable token authorization when login"
      shell: |
        kubectl apply -f bookinfo/authorization.yaml
      tags:
      - enable_authorization
      